name: save-logs
description: "Save debug logs"

runs:
  using: composite
  steps:
    - name: Fix log permissions
      run: |
        sudo chown $USER /tmp/zarf-*.log
      shell: bash

    - uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
      with:
        name: debug-log
        path: /tmp/zarf-*.log
