apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-redirector
  namespace: zarf
  labels:
    app: agent-redirector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-redirector
  template:
    metadata:
      labels:
        app: agent-redirector
        # Don't mutate this pod, that would be sad times
        zarf.dev/agent: ignore
    spec:
      imagePullSecrets:
        - name: private-registry
      containers:
        - name: server
          image: "###ZARF_REGISTRY###/###ZARF_CONST_AGENT_IMAGE###"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
          ports:
            - containerPort: 8443
            - containerPort: 8444
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
              readOnly: true
            - name: zarf-state
              mountPath: /etc/zarf-state
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: agent-redirector-tls
        - name: zarf-state
          secret:
            secretName: zarf-state
