# Hotfix some images until they are fixed upstream

# https://repo1.dso.mil/big-bang/product/packages/monitoring/-/merge_requests/191
monitoring:
  enabled: true
  git:
    # BB Upstream requires a branch with a commit hash for some reason... 
    # https://repo1.dso.mil/big-bang/bigbang/-/commit/f0175279cc65ce5095ac687f98b4133fabf96d67
    tag: ""
    branch: "main"

# loki:
#   git:
#     tag: ""
#     branch: "update-loki-tag-annotations"

# promtail:
#   git:
#     tag: ""
#     branch: "main"
