name: Analyze CVEs

permissions:
  contents: read

on:
  schedule:
    - cron: "0 10 * * *"
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
      - "package.json"
      - "package-lock.json"
      - "cargo.toml"
      - "cargo.lock"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Install tools
        uses: ./.github/actions/install-tools

      - name: Check for CVEs in Dependencies
        run: "make test-cves"
