name: Test Big Bang extension
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "package.json"
      - "package-lock.json"
      - "CODEOWNERS"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-bb-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Setup NodeJS
        uses: ./.github/actions/node

      - name: Build binary and zarf packages
        uses: ./.github/actions/packages

      - name: Setup K3d
        uses: ./.github/actions/k3d

      - name: "Login to Iron Bank "
        uses: docker/login-action@v2
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.IRONBANK_USERNAME }}
          password: ${{ secrets.IRONBANK_PASSWORD }}

      # @todo(jeff-mccoy) - Add previous version test once CRD upgraade support is fixed in zarf and BB 1.55 is exists
      - name: Run tests
        run: |
          # Get the Big Bang release versions
          project="2872"
          releases=$(curl -s https://repo1.dso.mil/api/v4/projects/$project/repository/tags | jq -r '[.[] | select(.name | test("^[^-]+$")) | .name][0:2] | .[]')
          latest=$(echo "$releases" | awk 'NR==1')
          previous=$(echo "$releases" | awk 'NR==2')

          echo "Latest: $latest"
          echo "Previous: $previous"

          export PATH=$(pwd)/build:$PATH

          # Build the packages
          zarf package create src/extensions/bigbang/test/package --set=BB_VERSION=$latest --confirm

          # Initialize the cluster
          zarf init --confirm --components git-server

          # Deploy the latest version
          zarf package deploy zarf-package-big-bang-test-amd64-$latest.tar.zst --confirm

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
